michaelapp/urls.py
from django.urls import path, include
from . import views

app_name = "michaelapp"

urlpatterns = [
    path('', views.index, name='index'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('about/', views.about, name='about'),
    path('hireMe/', views.hireMe, name='hireMe'),
]

story4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('michaelapp.urls')),
]

michaelapp/models.py
from django.db import models

# Create your models here.

michaelapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
	return render(request, 'index.html')

def portfolio(request):
	response = {'':''}
	return render(request, 'portfolio.html')

def about(request):
	response = {'':''}
	return render(request, 'about.html')

def hireMe(request):
	response = {'':''}
	return render(request, 'hire-me.html')

michaelapp/templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<header class="headline">
	<h1>About Michael</h1>
</header>

<section class="about-section">
	<img src="{% static 'img/michaelsusanto-profile.png' %}" alt="Michael's Profile Picture" class="prof-pic">
	<article>
		<h3>Greetings!</h3>
		<p>My name is Michael Susanto, i'm from Faculty of Computer Science,</p>
		<p>Universitas Indonesia.</p>

		<p>I started my programming career at St.Andrew Junior High School with</p>
		<p>Visual Basic 6.0 and design career at Sang Timur Senior High School.</p>
		<p>I've been studying web designing and web developing since my second</p>
		<p>semester in Universitas Indonesia.</p>

		<p>Beside programming, I usually play musical instruments to refresh my mind,</p>
		<p>and play badminton with friends to keep me healthy.</p>
	</article>		
</section>

{% endblock %}

michaelapp/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>Michael Susanto</title>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Berkshire+Swash|Ubuntu&display=swap" rel="stylesheet">
</head>
<body>
	<nav class="navbar" id="nav">
		<a href="{% url 'michaelapp:index' %}" class="navbar-brand">
			<h2>Michael</h2>
		</a>
		<ul class="navbar-nav d-inline-block">
			<li class="nav-item d-inline-block">
				<a href="{% url 'michaelapp:index' %}" class="nav-link">Home</a>
			</li>
			<li class="nav-item d-inline-block">
				<a href="{% url 'michaelapp:portfolio' %}" class="nav-link">Portfolio</a>
			</li>
			<li class="nav-item d-inline-block">
				<a href="{% url 'michaelapp:about' %}" class="nav-link">About</a>
			</li>
			<li class="nav-item d-inline-block">
				<a href="{% url 'michaelapp:hireMe' %}" class="nav-link">Hire Me</a>
			</li>
		</ul>
	</nav>

	{% block content %}

	{% endblock %}

	<footer>
		<h3>Find me on</h3>		
		<ul class="contacts">
			<li class="contact">
				<a href="https://www.facebook.com/michael.s.155">
					<img src="{% static 'img/fb-logo.png' %}" alt="Facebook's Logo">
				</a>
			</li>
			<li class="contact">
				<a href="https://www.youtube.com/channel/UC5325r3vONhMKz9QTXlPm2g">
					<img src="{% static 'img/youtube-logo.png' %}" alt="Youtube's Logo">
				</a>
			</li>
			<li class="contact">
				<a href="https://github.com/michaelsusanto81">
					<img src="{% static 'img/github-logo.png' %}" alt="Github's Logo">
				</a>
			</li>
			<li class="contact">
				<a href="https://id.linkedin.com/in/michael-susanto-292671193?trk=people-guest_profile-result-card_result-card_full-click">
					<img src="{% static 'img/linkedin-logo.png' %}" alt="LinkedIn's Logo">
				</a>
			</li>
		</ul>
		<h5>© 2019 <a href="#nav">Michael Susanto</a>.</h5>
	</footer>

</body>
</html>

michaelapp/templates/hire-me.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<header class="headline">
	<h1>Let me help you.</h1>
	<h2>I can build website.</h2>
</header>

<section class="about-section">
	<img src="{% static 'img/michaelsusanto-profile.png' %}" alt="Michael's Profile Picture" class="prof-pic">
	<article class="email">
		<a href="mailto:michael.susanto81@ui.ac.id">Email me</a>
	</article>		
</section>

{% endblock %}

michaelapp/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<header>
	<div class="bg-circle">
		<h1>Michael Susanto</h1>
		<h3>Web Developer</h3>
	</div>		
</header>

<section class="intro">
	<img src="{% static 'img/michaelsusanto-profile.png' %}" alt="Michael's Profile Picture" class="prof-pic">
	<h3>Hello!</h3>
	<h4>I'm a Junior Web Developer from</h4>
	<h4>Indonesia. I do design and develop</h4>
	<h4>web.</h4>
</section>

<section class="skills">
	<h3>I'm good at</h3>
	<div class="skills-layout">
		<ul class="left-skills">
			<li class="skill">
				<img src="{% static 'img/python-logo.png' %}" alt="Python's Logo">
				<h2>Python</h2>
			</li>
			<li class="skill">
				<img src="{% static 'img/html-logo.png' %}" alt="HTML's Logo">
				<h2>HTML</h2>
			</li>			
		</ul>
		<ul class="middle-skills">
			<li class="skill">
				<img src="{% static 'img/java-logo.png' %}" alt="Java's Logo">
				<h2>Java</h2>
			</li>			
			<li class="skill">
				<img src="{% static 'img/css-logo.png' %}" alt="CSS's Logo">
				<h2>CSS</h2>
			</li>			
		</ul>
		<ul class="right-skills">
			<li class="skill">
				<img src="{% static 'img/js-logo.png' %}" alt="JavaScript's Logo">
				<h2>JavaScript</h2>
			</li>
			<li class="skill">
				<img src="{% static 'img/ruby-logo.png' %}" alt="Ruby's Logo">
				<h2>Ruby</h2>
			</li>
		</ul>
	</div>			
</section>

{% endblock %}	

michaelapp/templates/portfolio.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<header class="headline">
	<img src="{% static 'img/michaelsusanto-profile.png' %}" alt="Michael's Profile Picture" class="prof-pic">
	<h1>Michael's Portfolio</h1>
	<h2>Here's what I have been to</h2>
</header>

<div class="portfolio-container">
	<section class="portfolio-section">
		<h2>Work</h2>
		<article class="portfolio-content">
			<img src="{% static 'img/teaching-assistant-logo.png' %}" alt="Teaching Assistant's Logo" class="portfolio-icon">
			<div class="portfolio-text">
				<h3>Undergraduate Teaching Assistant</h3>
				<h4>Programming Foundation 1 International Undergraduate</h4>
				<h4>at Faculty of Computer Science, Universitas Indonesia.</h4>
			</div>
		</article>
	</section>

	<section class="portfolio-section">
		<h2>Projects</h2>
		<article class="portfolio-content">
			<img src="{% static 'img/seapay-logo.png' %}" alt="Seapay's Logo" class="portfolio-icon">
			<div class="portfolio-text">
				<h3>SEA-PAY</h3>
				<h4>An online wallet mobile app. Built for Software</h4>
				<h4>Engineering Academy COMPFEST team's final project.</h4>
			</div>
		</article>
		<article class="portfolio-content">
			<a href="https://michaelsusanto81.github.io/RockPaperScissor/" target="_blank">
				<img src="{% static 'img/janken-logo.png' %}" alt="Rock-Paper-Scissors's logo" class="portfolio-icon">
			</a>
			<div class="portfolio-text">
				<h3>Rock Paper Scissors Game</h3>
				<h4>An online rock-paper-scissors game built by myself.</h4>
			</div>
		</article>
	</section>

	<section class="portfolio-section">
		<h2>Organizational</h2>
		<article class="portfolio-content">
			<img src="{% static 'img/weekend-logo.png' %}" alt="Weekend's Logo" class="portfolio-icon">
			<div class="portfolio-text">
				<h3>Weekend 2019 KUKSA Fasilkom UI</h3>
				<h4>An event that is a part of PMB Fasilkom UI 2019. I'm here</h4>
				<h4>as head of business funds and consumption.</h4>
			</div>
		</article>
	</section>
</div>

{% endblock %}